# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: smtp.sendgrid.net:587
mail_admin: cedreo@gmail.com
mail_hostname: cedreo-designer.com
mail_user: cedreo
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
