# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: nadxZvmx

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: Chntr1trdtOpblc
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  cedreo-designer.com:
    env:
      db_password: UZ6vz7eB
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "JQs8N;jV6vYFnuS._2Yqo)?oXz%Ca+#zXWGl8^8jD=/kf;UcO/xl4r/[2(IS@cjn"
      secure_auth_key: "$3|Kb&Lz`<&=ku=Y^}}8f<KE)]/CZ)l^ZyjT2?,stM&VCr;zV-HRgu-]422ccs2b"
      logged_in_key: "bZxK>FDM7o/D0a>AB3+%9#wt+2i:Nz<Rac;N9j/b$^FGn=_X]meR2<Hi2X(QY!Tq"
      nonce_key: "eK*km^%cm;IJmI:#7&6b`Zvy-jlqZ^J(c6DXl6MW]&}6!*]dA}`%OOhmhjMSmGn}"
      auth_salt: "XkzYLHQGFM@<y93A8,Er+9oNy(.C55+jbm;H!+U]2Z<dq+{V0C5)%(E|st]?EJ0R"
      secure_auth_salt: "8F;M#Z27xifGAL@90zi76LeKyud=yUe^4KJJ66::IviFAyILl|>[YEO-t.D-Z<uB"
      logged_in_salt: "[VYKU+edNPdL#{(5*JYQ.,GUC}2,-ta/<QH`baL_mCoO,VVnbs&w#w{EW=V:]LOH"
      nonce_salt: "Q&0`G?N=B0uQ8NUqytx!<#<O@O:v;bS6y$E,l.1XInuL07H][OTGsSL@!OOsFO7m"
